### ISSUE TITLE
Expose more metrics

### ISSUE THREAD

**Issue by jtheo** [prometheus-community/ecs_exporter#16]
Could also export other metrics like running, pending and desired number for the task?

It'll be also awesome if it could export the OOM events, but not sure it is possible.
It's more of a question for the ECS team to expose the metrics?

**Comment by rakyll** [comment]
The metadata server currently don't expose them and I suggest filing a feature request at https://github.com/aws/containers-roadmap/issues to capture what's needed. I work with the ECS team but it'd be easier to collaborate with the rest of team by using their communication channels.

**Comment by zied-elouaer** [comment]
It seems the metadata endpoint now has all the required information to add plenty of metrics here.

See:
https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html

Any chance this could be picked up again?

**Comment by zahornyak** [comment]
Hi, could you add some storage metrics?
