### ISSUE TITLE
Release 0.2.0 - Multiple Issues

### ISSUE THREAD

**Issue by jseiser** [prometheus-community/ecs_exporter#40]
@SuperQ 
@roidelapluie 
@sysadmind

I think the latest release broke, most things.

Steps to reproduce:

1. Deploy 0.2.0 into ECS fargate. `image : "quay.io/prometheuscommunity/ecs-exporter:v0.2.0"`
2. Curl the endpoint. `curl 10.1.110.149:9779/metrics > metrics.txt`

What we are seeing.

1. Memory metrics all return 0 now.

```
# HELP ecs_memory_bytes Memory usage in bytes.
# TYPE ecs_memory_bytes gauge
ecs_memory_bytes{container="console"} 0
ecs_memory_bytes{container="log_router"} 0
ecs_memory_bytes{container="nginx"} 0
ecs_memory_bytes{container="prom_exporter"} 0
# HELP ecs_memory_cache_usage Memory cache usage in bytes.
# TYPE ecs_memory_cache_usage gauge
ecs_memory_cache_usage{container="console"} 0
ecs_memory_cache_usage{container="log_router"} 0
ecs_memory_cache_usage{container="nginx"} 0
ecs_memory_cache_usage{container="prom_exporter"} 0
# HELP ecs_memory_limit_bytes Memory limit in bytes.
# TYPE ecs_memory_limit_bytes gauge
ecs_memory_limit_bytes{container="console"} 0
ecs_memory_limit_bytes{container="log_router"} 0
ecs_memory_limit_bytes{container="nginx"} 0
ecs_memory_limit_bytes{container="prom_exporter"} 0
# HELP ecs_memory_max_bytes Maximum memory usage in bytes.
# TYPE ecs_memory_max_bytes gauge
ecs_memory_max_bytes{container="console"} 0
ecs_memory_max_bytes{container="log_router"} 0
ecs_memory_max_bytes{container="nginx"} 0
ecs_memory_max_bytes{container="prom_exporter"} 0
```

2. The CPU metrics do not even show up.

```
[automation@ip-10-1-118-213 ecs-service-discovery]$ grep cpu metrics.txt
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.14
```

**Comment by jseiser** [comment]
Same image with the `main` image.

**Comment by jseiser** [comment]
The only log generated

```
{
    "container_id": "50ab69a6813f4ceca8b38402f74d86ae-33489729",
    "container_name": "prom_exporter",
    "deployment_id": "JLS",
    "ecs_cluster": "TREx-Foundation_DEV_JLS",
    "ecs_task_arn": "arn:aws-us-gov:ecs:us-gov-west-1:053166900151:task/TREx-Foundation_DEV_JLS/50ab69a6813f4ceca8b38402f74d86ae",
    "ecs_task_definition": "Foundation-DEV-JLS-Console:27",
    "environment": "DEV",
    "layer": "console",
    "log": "2022/08/08 19:56:34 Starting server at \":9779\"",
    "source": "stderr"
}
```

**Comment by SuperQ** [comment]
Hmm. It would help to have a debug log and an example ECS  API request so we can try and reproduce it.

**Comment by jseiser** [comment]
>  Hmm. It would help to have a debug log and an example ECS API request so we can try and reproduce it.


@SuperQ 

If you can tell me how to generate what you want, I can get it.

**Comment by jseiser** [comment]
@SuperQ 

While waiting for further instruction, I did revert to the older 0.1.1 image, and can confirm the metrics return, the CPU ones are just incorrect as we know.

```
[automation@ip-10-1-118-213 ecs-service-discovery]$ curl 10.1.110.54:9779/metrics > metrics.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11530    0 11530    0     0  2251k      0 --:--:-- --:--:-- --:--:-- 2251k
[automation@ip-10-1-118-213 ecs-service-discovery]$ grep cpu metrics.txt
# HELP ecs_cpu_seconds_total Total CPU usage in seconds.
# TYPE ecs_cpu_seconds_total counter
ecs_cpu_seconds_total{container="console",cpu="0"} 5.834025195e+07
ecs_cpu_seconds_total{container="console",cpu="1"} 5.421806216e+07
ecs_cpu_seconds_total{container="log_router",cpu="0"} 6.18522212e+06
ecs_cpu_seconds_total{container="log_router",cpu="1"} 5.15301504e+06
ecs_cpu_seconds_total{container="nginx",cpu="0"} 7.73859699e+06
ecs_cpu_seconds_total{container="nginx",cpu="1"} 1.002344517e+07
ecs_cpu_seconds_total{container="prom_exporter",cpu="0"} 2.51195986e+06
ecs_cpu_seconds_total{container="prom_exporter",cpu="1"} 4.74037571e+06
```

```
[automation@ip-10-1-118-213 ecs-service-discovery]$ grep ecs_mem metrics.txt
# HELP ecs_memory_bytes Memory usage in bytes.
# TYPE ecs_memory_bytes gauge
ecs_memory_bytes{container="console"} 1.63786752e+08
ecs_memory_bytes{container="log_router"} 6.3922176e+07
ecs_memory_bytes{container="nginx"} 2.8196864e+07
ecs_memory_bytes{container="prom_exporter"} 2.6288128e+07
```

**Comment by SuperQ** [comment]
There should be an env var, `ECS_CONTAINER_METADATA_URI_V4`

```
curl -o stats.json "${ECS_CONTAINER_METADATA_URI_V4}/task/stats
curl -o task.json "${ECS_CONTAINER_METADATA_URI_V4}/task
```

**Comment by jseiser** [comment]
@SuperQ 

[stats.txt](https://github.com/prometheus-community/ecs_exporter/files/9293199/stats.txt)
[task.txt](https://github.com/prometheus-community/ecs_exporter/files/9293200/task.txt)

[metrics.txt](https://github.com/prometheus-community/ecs_exporter/files/9293211/metrics.txt)


This is with the NEW 0.2.0 image running. Notice I did have to scrub out some data, like account #'s etc.  Also, made them `.txt` since github wont allow you to upload `.json`  I also uploaded a metrics.  Ill revert to an older release, and post that so you can see the difference.

**Comment by SuperQ** [comment]
The important part is to have real json values from the API so we can write tests.

**Comment by jseiser** [comment]
> The important part is to have real json values from the API so we can write tests.

Are you asking me to provide something else?  If so im not understanding what?

The JSON provided in those text files are from the calls you requested.

**Comment by jseiser** [comment]
@SuperQ 

Let me know if there is anything I can provide for you on this.  I have env's in place I can use to test images with, I dont know Go well enough to provide much technical assistance.

Thank you.

**Comment by jseiser** [comment]
Sorry to be a bother, I understand this exporter doesn't appear to get much use, but any chance you can provide documentation on how to test this, so I can maybe try and poke at it?  

All of our ECS tasks now have broken memory and CPU metrics, where before we just had broken CPU metrics.

Thank you.

**Comment by jseiser** [comment]
Just wanted to check in and see if there was anything we can do to provide assistance.

Thanks,

**Comment by SuperQ** [comment]
Hey, I have been on vacation, so haven't had time to look into this. For now, running the old version and dividing the CPU results by 10000000 should work.

**Comment by jseiser** [comment]
@SuperQ 

Thanks for the update, and I hope your vacation went well.

I will revert to 1.1 and see if we can get the CPU stuff working.

I would like to again offer that if we could get a bit more info on the building/testing we could attempt to provide fixes from our side.  We have no go specific dev's, but we def. have dev's.

Thanks

**Comment by SuperQ** [comment]
If you can figure out where the parsing is going wrong, that'd be helpful.

I think the fixtures you provided should be sufficient to test with, I just haven't had a chance to make them into a unit test.

**Comment by jseiser** [comment]
@SuperQ  

I guess im asking more for how you guys do the testing, and building.  There is no documentation on it that I can find.  We have a stable of python dev's, and I have a bit of golang experience, so I imagine we could potentially cobble together some eyes on this.

**Comment by SuperQ** [comment]
Everything is done via our CI pipelines.

The testing in this exporter is pretty minimal, since it doesn't have access to a real AWS API.

We can add a simulated http response to the unit tests. That should prevent future issues.

**Comment by jseiser** [comment]
@SuperQ 

Any information on how we can build/test this locally would help.  Otherwise we are really just stuck here waiting/bugging you and I know you guys are busy.  We have dev's, just not Golang specific devs.

**Comment by jseiser** [comment]
>  Hey, I have been on vacation, so haven't had time to look into this. For now, running the old version and dividing the CPU results by 10000000 should work.

Im not sure what is correct here.


Like Cadvisor looks like

```
sum by (name) (irate(container_cpu_user_seconds_total{instance=~"$node",job=~"$job",image!="", name=~"$name"}[$__rate_interval]) / scalar(machine_cpu_cores{instance=~"$node",job=~"$job"}) ) * 100 
```

Python Prometheus Exporter looks like

```
rate(ecs_cpu_seconds_total{ecs_task_id="a94a0debf2c14362a6b4f22108d1ef12"}[30s])
```


Im not sure which model would work here, and which number should be divided?

**Comment by kvendingoldo** [comment]
Do we have any news here?

**Comment by jseiser** [comment]
@SuperQ 

Just wanted to check in on this one and see if there was anything additional we could provide?

**Comment by SuperQ** [comment]
Sorry, I've not had time to look into this recently. Someone needs to write some unit tests with data provided above so we can reproduce the issue.

**Comment by jseiser** [comment]
@SuperQ 

I just wanted to touch base on this one again, its still not working properly.

You posted above about working around the issue, but I wasn't really sure on how you were saying to do it.  This was on on Aug 24, 2022.  Any chance you can clarify what you meant?

As for writing the additional tests, if someone could provide more context I could probably get one of our dev's to take a stab at it.  Outside of knowing it runs in your CI pipelines, i didnt see much more than a large make file and it wasnt clear to me where to start investigating.


Also, Im not sure if this is volunteer work for you or not, if it is, is there anything we can do privately to push this one over the line?

Thanks,

**Comment by SuperQ** [comment]
Ok, fix is released, please give it a try.

**Comment by rkul** [comment]
I've tested it on several our ECS clusters, it looks good.
I see few another issues: CPU metrics require normalisation and memory limit returns 1^64 for Fargate tasks, where container memory limit isn't set explicitly. But the initial issue definitely solved.

<img width="1273" alt="Screenshot 2023-01-26 at 19 37 06" src="https://user-images.githubusercontent.com/5493637/214884104-0371d321-2f9e-4983-8803-3fefc9cea481.png">

<img width="1282" alt="Screenshot 2023-01-26 at 19 40 09" src="https://user-images.githubusercontent.com/5493637/214884139-cb866566-b577-452d-8975-6c23772bd812.png">

_*There are tasks on common graph that were terminated due to scale down_

**Comment by jseiser** [comment]
Any chance you can post the working queries? About to deploy this to our
ecs/far hate environments

Thanks

**Comment by rkul** [comment]
I did a bit of research and figured out that AWS updates Task Metadata with Docker stats every 10s, so `rate` is okay for that if you set interval like `1m`. Also, CPU utilization is in percents of one single core. So if you allocated something like `.25vCPU` for task/container, then 25% means full utilization.

```
sum by (ecs_task_arn)(rate(ecs_cpu_seconds_total{ecs_task_name="$app"}[$interval])) * 100
sum by (container,ecs_task_arn)(rate(ecs_cpu_seconds_total{ecs_task_arn="$task"}[$interval])) * 100
sum by (ecs_task_arn)(ecs_memory_bytes{ecs_task_name="$app"})/1024/1024
sum by (container,ecs_task_arn)(ecs_memory_bytes{ecs_task_arn="$task"})/1024/1024
```

**Comment by jseiser** [comment]
@rkul 

Do you know have any issues with the CPU not matching what is shown in Cloudwatch ?

**Comment by SuperQ** [comment]
FYI, you want to use `$__rate_interval` in Grafana.
