### ISSUE TITLE
Add option to disable exporter metrics

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/ecs_exporter#8]
Feature idea, similar to the node_exporter, we could add a flag to disable the built-in Go/process metrics for the exporter itself. With a large container fleet, they add a lot to the monitoring system load.

**Comment by jseiser** [comment]
This would be great for us as well.  We plan on running this exporter for every single ECS Task we have.  These tasks already containe a nginx/flask/fluentbit container per task, so this container will be the 4th.  Anything that can be done to reduce its usage requirements will be great.
