### ISSUE TITLE
Health check command

### ISSUE THREAD

**Issue by isker** [prometheus-community/ecs_exporter#88]
Unlike e.g. Kubernetes, ECS [does not support](https://github.com/aws/containers-roadmap/issues/1860) HTTP health checks.  Instead it can only perform health checks by executing a command in the container, similar to docker's HEALTHCHECK.

The exporter [exposes](https://github.com/prometheus-community/ecs_exporter/blob/64e73a40999d011a74c32681db09855cedd290b6/main.go#L95-L98) a simple "liveness" `/health` endpoint that would be suitable as an ECS health check, but the docker image for this project does not include any command that can make a request to this endpoint and transmute failures to a non-zero exit code, as ECS requires.  So, users that want such a thing need to build their own images with such an executable.

I think normally supporting this kind of thing would be out of scope for a prom exporter, but this exporter is only ever supposed to run in ECS, so it makes sense to cave to its demands.

Should we add a second, separate binary for such a command, or should we add a flag or subcommand to the existing exporter binary so that it can be invoked in this way?

**Comment by SuperQ** [comment]
The container image contains busybox, which has a `wget` command. That should be sufficient for doing health checks.

**Comment by isker** [comment]
Cripes you're right, I got my images twisted 🌞.
