### ISSUE TITLE
Container image tag is not available

### ISSUE THREAD

**Issue by rakyll** [prometheus-community/ecs_exporter#9]
@roidelapluie was mentioning that the VERSION number can be used to publish container images with a tag, but I currently see no tags available at quay.io/prometheuscommunity. We need to tag the image rather than suggesting users to pull from main.

**Comment by SuperQ** [comment]
The process follows the [Prometheus release process](https://github.com/prometheus/prometheus/blob/main/RELEASE.md#2-draft-the-new-release). Once the VERSION file and CHANGELOG.md are in sync and formatted correctly, you push a git tag and CircleCI will cut a release on GitHub and publish images.

**Comment by roidelapluie** [comment]
Yes, this repository has not been released yet. This is as expected.
